artifacts_root : artifacts


data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : https://drive.google.com/file/d/1lLbSqACVv2eC_kjKyqCLvy9Rn4y2qx7N/view?usp=sharing
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


base_model :
  root_dir : artifacts/prep_base_model
  base_model_path : artifacts/prep_base_model/base_model.h5
  updated_base_model_path : artifacts/prep_base_model/updated_base_model.h5


model_training :
  root_dir : artifacts/model_training
  trained_model_path : artifacts/model_training/training.h5


# model_evaluation :
#   root_dir  : artifacts/model_evaluation
#   model_evaluation_file_path : artifacts/model_evaluation/model_evaluation.yaml

